import os

DASHBOARD_SERVER_URL = os.environ['DASHBOARD_SERVER_URL']
API_SERVER_URL = os.environ['API_SERVER_URL']
API_AUTH_TOKEN = os.environ['API_AUTH_TOKEN']

LMS_URL = os.environ['LMS_URL']
LMS_USERNAME = os.environ['LMS_USERNAME']
LMS_PASSWORD = os.environ['LMS_PASSWORD']

BASIC_AUTH_USERNAME = os.environ.get('BASIC_AUTH_USERNAME')
BASIC_AUTH_PASSWORD = os.environ.get('BASIC_AUTH_PASSWORD')
BASIC_AUTH_CREDENTIALS = None

if BASIC_AUTH_USERNAME and BASIC_AUTH_PASSWORD:
    BASIC_AUTH_CREDENTIALS = (BASIC_AUTH_USERNAME, BASIC_AUTH_PASSWORD)
